name: deploy

inputs:
  env:
    required: true
  port:
    description: Application port
    required: true

runs:
  using: composite
  steps:
    - name: checkout python-greetings repository
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        ref: main
        clean: 'false'
        path: 'deploy'
    - run: echo "Running tests on ${{ inputs.env }}..."
      shell: cmd

    - name: Delete existing pm2 process
      shell: cmd
      working-directory: ./deploy
      run: pm2 delete greetings-app-${{ inputs.env }} || exit /b 0

    - name: pwd
      shell: cmd
      working-directory: ./deploy
      run: dir

    - name: Start new pm2 process
      shell: cmd
      run: pm2 start %CD%\deploy\app.py --name greetings-app-${{ inputs.env }} --interpreter %CD%\python\venv\Scripts\python.exe -- --port ${{ inputs.port }}

    - name: Finish stage
      shell: cmd
      working-directory: ./deploy
      run: echo "Deployment to ${{ inputs.env }} environment finished successfully."